## Aula de Data Science

In [3]:
import pandas as pd

uri = "https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula4.1/movies.csv"
filmes = pd.read_csv(uri)
filmes.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [4]:
filmes.columns

Index(['movieId', 'title', 'genres'], dtype='object')

In [5]:
filmes.columns = ["filmeId", "titulo", "generos"]
filmes.head()

filmeId                              titulo  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                       generos  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [6]:
uri = "https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula4.1/ratings.csv"
notas = pd.read_csv(uri)
notas.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [7]:
notas.columns = ["usuarioId", "filmeId", "nota", "momento"]
notas.head()

usuarioId  filmeId  nota    momento
0          1        1   4.0  964982703
1          1        3   4.0  964981247
2          1        6   4.0  964982224
3          1       47   5.0  964983815
4          1       50   5.0  964982931

In [9]:
notas["nota"] # Series

0         4.0
1         4.0
2         4.0
3         5.0
4         5.0
         ... 
100831    4.0
100832    5.0
100833    5.0
100834    5.0
100835    3.0
Name: nota, Length: 100836, dtype: float64

In [11]:
notas["nota"].unique()

array([4. , 5. , 3. , 2. , 1. , 4.5, 3.5, 2.5, 0.5, 1.5])

In [12]:
notas["nota"].mean()

3.501556983616962

In [13]:
notas["nota"].min()

0.5

In [14]:
notas.describe()

usuarioId        filmeId           nota       momento
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

## Matrizes

In [21]:
import numpy as np
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
c.ndim

2

In [23]:
c[0, 1]

2

In [24]:
c[2, 1]

8

In [25]:
c.shape

(3, 3)

In [26]:
c.shape[0]

3

In [27]:
c.shape[1]

3

### Extraindo uma submatriz

In [28]:
c[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
c[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [32]:
c[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [33]:
c[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
c[0:2].shape

(2, 3)

In [35]:
c[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [36]:
c[:,1:2]

array([[2],
       [5],
       [8]])

In [37]:
c[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [38]:
c[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [39]:
c[0,1]

2

In [40]:
c[0,1] = 20

In [41]:
c

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [42]:
c[0:1, 0:1] = np.array([300])

In [43]:
c

array([[300,  20,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [44]:
c[0:1] = np.array([3, 2, 1])
c

array([[3, 2, 1],
       [4, 5, 6],
       [7, 8, 9]])

### Matrizes especiais

In [47]:
# MATRIZ IDENTIDADE
# Matriz quadrada (perfeita) que em sua diagonal principal é composta por algarismo 1.

i = np.eye(3) # 3 linhas e 3 colunas
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
# MATRIZ DE ZEROS
# Matriz composta somente por zeros.

zeros = np.zeros([3, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
# MATRIZ DE UMS
# Matriz composta somente por ums.

ums = np.ones([3, 3])
ums

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])