## Aula de Data Science

In [2]:
import pandas as pd

uri = "https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula4.1/movies.csv"
filmes = pd.read_csv(uri)
filmes.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [3]:
filmes.columns

Index(['movieId', 'title', 'genres'], dtype='object')

In [4]:
filmes.columns = ["filmeId", "titulo", "generos"]
filmes.head()

filmeId                              titulo  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                       generos  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [5]:
uri = "https://raw.githubusercontent.com/alura-cursos/introducao-a-data-science/master/aula4.1/ratings.csv"
notas = pd.read_csv(uri)
notas.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [6]:
notas.columns = ["usuarioId", "filmeId", "nota", "momento"]
notas.head()

usuarioId  filmeId  nota    momento
0          1        1   4.0  964982703
1          1        3   4.0  964981247
2          1        6   4.0  964982224
3          1       47   5.0  964983815
4          1       50   5.0  964982931

In [7]:
notas["nota"] # Series

0         4.0
1         4.0
2         4.0
3         5.0
4         5.0
         ... 
100831    4.0
100832    5.0
100833    5.0
100834    5.0
100835    3.0
Name: nota, Length: 100836, dtype: float64

In [8]:
notas["nota"].unique()

array([4. , 5. , 3. , 2. , 1. , 4.5, 3.5, 2.5, 0.5, 1.5])

In [9]:
notas["nota"].mean()

3.501556983616962

In [10]:
notas["nota"].min()

0.5

In [11]:
notas.describe()

usuarioId        filmeId           nota       momento
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

## Matrizes

In [12]:
import numpy as np
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
c.ndim

2

In [14]:
c[0, 1]

2

In [15]:
c[2, 1]

8

In [16]:
c.shape

(3, 3)

In [17]:
c.shape[0]

3

In [18]:
c.shape[1]

3

### Extraindo uma submatriz

In [19]:
c[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
c[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [21]:
c[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [22]:
c[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
c[0:2].shape

(2, 3)

In [24]:
c[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [25]:
c[:,1:2]

array([[2],
       [5],
       [8]])

In [26]:
c[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [27]:
c[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [28]:
c[0,1]

2

In [29]:
c[0,1] = 20

In [30]:
c

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
c[0:1, 0:1] = np.array([300])

In [32]:
c

array([[300,  20,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [33]:
c[0:1] = np.array([3, 2, 1])
c

array([[3, 2, 1],
       [4, 5, 6],
       [7, 8, 9]])

### Matrizes especiais

In [34]:
# MATRIZ IDENTIDADE
# Matriz quadrada (perfeita) que em sua diagonal principal é composta por algarismo 1.

i = np.eye(3) # 3 linhas e 3 colunas
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# MATRIZ DE ZEROS
# Matriz composta somente por zeros.

zeros = np.zeros([3, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
# MATRIZ DE UMS
# Matriz composta somente por ums.

ums = np.ones([3, 3])
ums

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
# ARREY COM UM DETERMINADO ELEMENTO

d = np.full((4, 5), 10) #(4, 5) é o shape 4 linhas por 5 colunas que vão
                        # ser preenchidos por 10.       
d

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [39]:
# MATRIZ DIAGONAL
# Diferente da matriz de identidade, a matriz diagonal pode receber
# quaisquer números em uma mesma matriz.

matriz = np.diag([1, 2, 3, 4, 5, 6, 7, 8, 9])
matriz

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [42]:
# MATRIZ COM TERMOS REPETIDOS

matriz = np.tile([[1, 2], [3, 4], [5, 6]], (3, 2)) # (3, 2) é o shape onde 3 repete as
                                                   # linhas e 2 irá repetir as colunas.
matriz

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6]])

## Tipagem de Dados
**dype** - fornece qual tipo de dado está armazenado na estrutura

In [43]:
e = np.array([1, 2, 3, 4, 5])
e

array([1, 2, 3, 4, 5])

In [44]:
e.dtype

dtype('int32')

In [45]:
f = np.array(['a', 'b', 'c', 'd'])
f

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [46]:
f.dtype

dtype('<U1')

In [47]:
g = np.array([False, True, False])
g

array([False,  True, False])

In [48]:
g.dtype

dtype('bool')

## CAST DE DADOS

In [49]:
h = np.array([9, 8, 7, 6])
h

array([9, 8, 7, 6])

In [50]:
h.dtype

dtype('int32')

In [52]:
h = h.astype(float)

In [53]:
h

array([9., 8., 7., 6.])

In [54]:
h.dtype

dtype('float64')

## Operações Aritméticas com Arrays

In [55]:
k = np.arange(0, 10)
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
h = np.arange(0, 10)
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
k + h

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
h - k

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
k = h

In [61]:
k * h

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [62]:
k == h

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [63]:
k > h

array([False, False, False, False, False, False, False, False, False,
       False])

In [64]:
k < h

array([False, False, False, False, False, False, False, False, False,
       False])

In [65]:
array1 = np.array([True,  True, True])
array2 = np.array([False, True, False])
np.logical_and(array1, array2)

array([False,  True, False])

In [68]:
np.logical_or(array1, array2)

array([ True,  True,  True])

## CÓPIAS DE ARRAYS

In [81]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.copy()

In [70]:
b

array([1, 2, 3, 4, 5, 6])

In [71]:
a[0] = 10

In [72]:
a

array([10,  2,  3,  4,  5,  6])

In [82]:
b

array([1, 2, 3, 4, 5, 6])

In [76]:
c = a.copy()
c

array([1, 2, 3, 4, 5, 6])

In [77]:
a[0] = 20
a

array([20,  2,  3,  4,  5,  6])

In [83]:
b

array([1, 2, 3, 4, 5, 6])

In [84]:
c

array([1, 2, 3, 4, 5, 6])

## Operações aritiméticas com matrizes

In [85]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [86]:
a + b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [87]:
b - a

array([[ 8,  6,  4],
       [ 2,  0, -2],
       [-4, -6, -8]])

In [88]:
a + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [89]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [90]:
a * b

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

## ARRAY x MATRIX

In [91]:
z = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
z

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [92]:
z.shape

(3, 2, 3)

In [93]:
# y = np.matrix([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
# A função matrix comporta apenas arrays bidimencionais.
# A variavel y causaria um erro pois o array é tridimencional.