<a href="https://colab.research.google.com/github/albertomendess/Data-Science/blob/main/Basico_sobre_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ndarray: um objeto array multidimencional

In [ ]:
import numpy as np

In [ ]:
# Gera alguns dados aleatórios
data = np.random.randn(2, 3)
data

array([[ 0.11987817,  0.78598981,  0.83989505],
       [-1.95153853,  0.6188388 ,  0.25854129]])

In [ ]:
data * 10

array([[  1.19878171,   7.85989813,   8.39895051],
       [-19.51538529,   6.18838805,   2.58541287]])

In [ ]:
data + data

array([[ 0.23975634,  1.57197963,  1.6797901 ],
       [-3.90307706,  1.23767761,  0.51708257]])

In [ ]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


### Criando ndarrays

In [ ]:
data1 = [6, 7.5, 8, 0, 1]

In [ ]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [ ]:
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.empty((2, 3, 1))

array([[[0.23975634],
        [1.57197963],
        [1.6797901 ]],

       [[3.90307706],
        [1.23767761],
        [0.51708257]]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Tipos de dados para ndarray

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [ ]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [ ]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [ ]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [ ]:
arr = np.array([3.7, -1.2, -2.6, .5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [ ]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [ ]:
numeric_strings = np.array(['-1.25', '-9.25', '42'], dtype=np.string_)
numeric_strings.astype(np.float64)

array([-1.25, -9.25, 42.  ])

In [ ]:
int_array = np.arange(10)

In [ ]:
calibers = np.array([.22/ .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### Aritmética com Arrays NumPy

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [ ]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr2 = np.array([[0., 4., 1,], 
                 [7., 2., 12.]])

In [ ]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [ ]:
arr > arr2

array([[ True, False,  True],
       [False,  True, False]])

### indexação básica e fatiamento

In [ ]:
arr = np.arange(10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
arr[5:8]

array([5, 6, 7])

In [ ]:
arr[5:8] = 12

In [ ]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
arr_slice = arr[5:8]

In [ ]:
arr_slice

array([12, 12, 12])

In [ ]:
arr_slice[1] = 12345

In [ ]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [ ]:
arr_slice[:] = 64

In [ ]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

In [ ]:
arr2d[2]

array([7, 8, 9])

In [ ]:
arr2d[0][2]

3

In [ ]:
arr2d[0, 2]

3