<a href="https://colab.research.google.com/github/albertomendess/Data-Science/blob/main/Basico_sobre_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ndarray: um objeto array multidimencional

In [1]:
import numpy as np

In [2]:
# Gera alguns dados aleatórios
data = np.random.randn(2, 3)
data

array([[-0.87482113,  1.93530485,  0.97874764],
       [-0.90091047, -1.48259197,  0.63320496]])

In [3]:
data * 10

array([[ -8.74821134,  19.35304848,   9.78747639],
       [ -9.00910466, -14.82591967,   6.3320496 ]])

In [4]:
data + data

array([[-1.74964227,  3.8706097 ,  1.95749528],
       [-1.80182093, -2.96518393,  1.26640992]])

In [5]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


### Criando ndarrays

In [6]:
data1 = [6, 7.5, 8, 0, 1]

In [7]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [9]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [11]:
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.empty((2, 3, 1))

array([[[1.74964227],
        [3.8706097 ],
        [1.95749528]],

       [[1.80182093],
        [2.96518393],
        [1.26640992]]])

In [15]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Tipos de dados para ndarray

In [16]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [17]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [18]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [19]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [20]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [21]:
arr = np.array([3.7, -1.2, -2.6, .5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [22]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [23]:
numeric_strings = np.array(['-1.25', '-9.25', '42'], dtype=np.string_)
numeric_strings.astype(np.float64)

array([-1.25, -9.25, 42.  ])

In [24]:
int_array = np.arange(10)

In [25]:
calibers = np.array([.22/ .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### Aritmética com Arrays NumPy

In [27]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [28]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [30]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [32]:
arr2 = np.array([[0., 4., 1,], 
                 [7., 2., 12.]])

In [33]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [34]:
arr > arr2

array([[ True, False,  True],
       [False,  True, False]])

### indexação básica e fatiamento

In [35]:
arr = np.arange(10)

In [36]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[5]

5

In [38]:
arr[5:8]

array([5, 6, 7])

In [39]:
arr[5:8] = 12

In [40]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [41]:
arr_slice = arr[5:8]

In [42]:
arr_slice

array([12, 12, 12])

In [43]:
arr_slice[1] = 12345

In [44]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [45]:
arr_slice[:] = 64

In [46]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [47]:
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

In [48]:
arr2d[2]

array([7, 8, 9])

In [49]:
arr2d[0][2]

3

In [50]:
arr2d[0, 2]

3

In [51]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [52]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
old_values = arr3d[0].copy()

In [55]:
arr3d[0] = 42

In [56]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr3d[0] = old_values

In [58]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
x = arr3d[1, 0]
y = arr3d[1, 1]

In [60]:
x

array([7, 8, 9])

In [61]:
y

array([10, 11, 12])

## Indexando com fatias

In [62]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [63]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [64]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr2d[:1]

array([[1, 2, 3]])

In [66]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [67]:
arr2d[1, :2]

array([4, 5])

In [68]:
arr2d[:2, 2]

array([3, 6])

In [69]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [70]:
arr2d[:2, 1:] = 0

In [71]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Indexação booleana

In [72]:
names = np.array(['Bob', 'joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [73]:
data = np.random.randn(7, 4)

In [74]:
names

array(['Bob', 'joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [75]:
data

array([[-0.32474994,  0.73540226, -0.24077738, -1.89956193],
       [-0.50585335,  0.4510281 ,  0.44203003,  1.39430389],
       [ 2.06558705,  0.97632947, -0.29138126, -0.2777792 ],
       [ 0.13674028,  0.36087994, -0.32691355, -1.17224129],
       [ 0.31051022, -1.40564687,  2.14400218, -0.14131911],
       [-0.03190866, -0.72803267, -0.96496926, -0.2178832 ],
       [-0.06115653, -1.16124106, -0.11465117, -1.25078683]])

In [76]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [77]:
data[names == 'Bob']

array([[-0.32474994,  0.73540226, -0.24077738, -1.89956193],
       [ 0.13674028,  0.36087994, -0.32691355, -1.17224129]])

In [78]:
data[names == 'Bob', 2:]

array([[-0.24077738, -1.89956193],
       [-0.32691355, -1.17224129]])

In [79]:
data[names == 'Bob', 3:]

array([[-1.89956193],
       [-1.17224129]])

In [80]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [81]:
data[~(names == 'Bob')]

array([[-0.50585335,  0.4510281 ,  0.44203003,  1.39430389],
       [ 2.06558705,  0.97632947, -0.29138126, -0.2777792 ],
       [ 0.31051022, -1.40564687,  2.14400218, -0.14131911],
       [-0.03190866, -0.72803267, -0.96496926, -0.2178832 ],
       [-0.06115653, -1.16124106, -0.11465117, -1.25078683]])

In [82]:
cond = names == 'Bob'

In [83]:
data[~cond]

array([[-0.50585335,  0.4510281 ,  0.44203003,  1.39430389],
       [ 2.06558705,  0.97632947, -0.29138126, -0.2777792 ],
       [ 0.31051022, -1.40564687,  2.14400218, -0.14131911],
       [-0.03190866, -0.72803267, -0.96496926, -0.2178832 ],
       [-0.06115653, -1.16124106, -0.11465117, -1.25078683]])

In [84]:
mask = (names == 'Bob') | (names == 'Will')

In [85]:
mask

array([ True, False,  True,  True,  True, False, False])

In [86]:
data[mask]

array([[-0.32474994,  0.73540226, -0.24077738, -1.89956193],
       [ 2.06558705,  0.97632947, -0.29138126, -0.2777792 ],
       [ 0.13674028,  0.36087994, -0.32691355, -1.17224129],
       [ 0.31051022, -1.40564687,  2.14400218, -0.14131911]])

In [87]:
data[data < 0] = 0

In [88]:
data

array([[0.        , 0.73540226, 0.        , 0.        ],
       [0.        , 0.4510281 , 0.44203003, 1.39430389],
       [2.06558705, 0.97632947, 0.        , 0.        ],
       [0.13674028, 0.36087994, 0.        , 0.        ],
       [0.31051022, 0.        , 2.14400218, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [89]:
data[names != 'Joe'] = 7

In [90]:
data

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Indexação sofisticada

In [91]:
arr = np.empty((8, 4))

In [92]:
for i in range(8):
    arr[i] = i

In [93]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [94]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [95]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [96]:
arr = np.arange(32).reshape((8, 4))

In [97]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [98]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [100]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## Transposição de arrays e troca de eixos

In [101]:
arr = np.arange(15).reshape((3, 5))

In [102]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [103]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [104]:
arr = np.random.randn(6, 3)

In [105]:
arr

array([[ 0.24543343,  1.72649992, -1.23426587],
       [ 0.5291449 , -0.35784265, -0.22653107],
       [ 1.21769173,  0.16841629,  0.54101562],
       [-0.19231627, -1.1431645 ,  1.10985878],
       [-0.12971286, -0.48807634,  0.26908242],
       [-0.24854835,  0.8120196 ,  1.96775077]])

In [106]:
np.dot(arr.T, arr)

array([[ 1.93859229,  0.52080208, -0.50143618],
       [ 0.52080208,  5.34163681, -1.76101335],
       [-0.50143618, -1.76101335,  7.04366141]])

In [107]:
arr = np.arange(16).reshape((2, 2, 4))

In [108]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [109]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [110]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [111]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Funções universais: funções rápidas de arrays para todos os elementos