<a href="https://colab.research.google.com/github/albertomendess/Data-Science/blob/main/TESTES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### OPERAÇÕES ESCALARES EVETORIAIS

In [2]:
myVect = np.array([1, 2, 3, 4])
myVect

array([1, 2, 3, 4])

In [3]:
myVect = np.array(np.int16([1, 2, 3, 4]))
myVect

array([1, 2, 3, 4], dtype=int16)

In [6]:
myVect = np.zeros(4, dtype= np.int16)
myVect

array([0, 0, 0, 0], dtype=int16)

In [8]:
myVect = np.array([1, 2, 3, 4])

In [9]:
myVect + 1

array([2, 3, 4, 5])

In [10]:
myVect = np.array(np.int16([1, 2, 3, 4]))

In [11]:
myVect + 1

array([2, 3, 4, 5], dtype=int16)

In [12]:
myVect - 1

array([0, 1, 2, 3], dtype=int16)

In [13]:
2 ** myVect

array([ 2,  4,  8, 16], dtype=int16)

In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

In [16]:
a == b

array([False,  True, False,  True])

In [18]:
a <= b

array([ True,  True,  True,  True])

In [19]:
a < b

array([ True, False,  True, False])

In [20]:
c = np.array([True, False, True, False])
d = np.array([True, True, False, False])

In [25]:
np.logical_or(c, d)

array([ True,  True,  True, False])

In [26]:
np.logical_and(c, d)

array([ True, False, False, False])

In [27]:
np.logical_not(c)

array([False,  True, False,  True])

In [28]:
np.logical_xor(a, b)

array([False, False, False, False])

### EXECUTANDO A MULTIPLICAÇÃO VETORIAL

In [29]:
myVect = np.array([1, 2, 3, 4])

In [30]:
np.multiply(myVect, myVect)

array([ 1,  4,  9, 16])

In [31]:
myVect.dot(myVect)

30

### CRIANDO UMA MATRIZ

In [51]:
# Matriz bidimencional
myMatrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
myMatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
myMatrix[0, 0]

1

In [52]:
# Matriz tridimencional
myMatrix = np.array([[[1,  2], [3,  4]],
                     [[5,  6], [7,  8]],
                     [[9, 10], [11, 12]]])
myMatrix

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [48]:
myMatrix[2, 1, 1]

12

In [50]:
myMatrix = np.ones([4, 4], dtype= np.int32)
myMatrix

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [55]:
myMatrix = np.ones([4, 4, 4], dtype= np.bool)
myMatrix

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [57]:
myMatrix = np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
myMatrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
myMatrix = np.asarray(myMatrix)

In [59]:
myMatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
myMatrix = np.asmatrix(myMatrix)

In [61]:
myMatrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [65]:
myMatrix = np.zeros([3, 3], dtype= np.int32)
myMatrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [67]:
myMatrix = np.asmatrix(myMatrix)
myMatrix

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=int32)